apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bee-gate-test.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bee-gate-test.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bee-gate-test.name" . }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.pod.fsGroup }}
      containers:
        - name: bee-gate-test
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BEE_GATE_TEST_NATS_SERVERS
              value: {{ .Values.nats.servers | quote }}
            - name: BEE_GATE_TEST_NATS_NAME
              value: {{ .Values.nats.name | quote }}
            - name: BEE_GATE_TEST_SUBJECT
              value: {{ .Values.subject | quote }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
